### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by younis98** [huckiyang/interconnect-routing-gym#1]
Hii @felix0901 
Could you provide the Dataset You are working on.
Thanks in advance.

**Comment by huckiyang** [comment]
Hi @younis98, thank you for your interests!
@felix0901 and I have a discussion - we will mostly also release the build file for gem5 simulator soon.

**Comment by felix0901** [comment]
We use the synthesis dataset, which you can find [here](http://pwp.gatech.edu/ece-tushar/wp-content/uploads/sites/175/2019/01/Lab1.pdf).

**Comment by huckiyang** [comment]
@younis98 see https://github.com/felix0901/interconnect-routing-gym/blob/master/src/icn_gym.py#L30
